#!/usr/bin/env python3
"""
AP_FLAKE8_CLEAN
Tests for the Vector gimbal kinematics.

Run with the standard library only, no virtualenv needed::

    python3 -m unittest discover -s Vector/tests -v

The suite also owns the golden vectors that the TypeScript port is checked
against, so a sign flip in one language cannot pass unnoticed in the other.
Regenerate them with::

    python3 Vector/tests/test_kinematics.py --write-golden
"""

from __future__ import annotations

import json
import math
import os
import sys
import unittest

REPO_ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
sys.path.insert(0, os.path.join(REPO_ROOT, "Vector", "dashboard"))

from server import config as vconfig  # noqa: E402
from server import kinematics as kin  # noqa: E402

GOLDEN_PATH = os.path.join(REPO_ROOT, "Vector", "tests", "golden_kinematics.json")

# The eight (outer_servo_deg, inner_servo_deg) pairs the retired north_bench
# dashboard used as its full-deflection compass points. They are reproduced here so
# the explicit kinematics are provably a drop-in replacement for that lookup table
# rather than a new set of conventions.
LEGACY_CARDINALS = {
    "N": (0.0, 45.0),
    "NE": (-45.0, 0.0),
    "E": (-45.0, -45.0),
    "SE": (-45.0, -90.0),
    "S": (0.0, -45.0),
    "SW": (45.0, 0.0),
    "W": (45.0, 45.0),
    "NW": (45.0, 90.0),
}


def build_golden(cfg: vconfig.VehicleConfig) -> dict:
    return {
        "note": "Generated by Vector/tests/test_kinematics.py. Do not edit by hand.",
        "arms": {arm.id: kin.golden_vectors(arm) for arm in cfg.arms},
    }


class KinematicsTest(unittest.TestCase):
    cfg: vconfig.VehicleConfig
    north: vconfig.ArmConfig

    @classmethod
    def setUpClass(cls) -> None:
        cls.cfg = vconfig.load()
        cls.north = cls.cfg.arm("north")

    def close(self, got: float, want: float, tol: float = 1e-9, msg: str = "") -> None:
        self.assertAlmostEqual(got, want, delta=tol, msg=msg or f"{got} != {want}")

    # ------------------------------------------------------------------
    # config
    # ------------------------------------------------------------------
    def test_config_loads_all_arms(self) -> None:
        self.assertEqual([arm.id for arm in self.cfg.arms], ["north", "east", "south", "west"])
        self.assertTrue(self.cfg.arm("north").live)
        self.assertEqual(self.cfg.frame.layout, "plus")

    def test_arms_inherit_gimbal_defaults(self) -> None:
        """
        An arm entry only names its channels; geometry comes from the defaults block.

        Asserted against the defaults as they sit in the document rather than against
        copied literals, so tuning the vehicle does not break the test that proves
        inheritance works.
        """
        defaults = self.cfg.raw["gimbal_defaults"]
        for arm in self.cfg.arms:
            with self.subTest(arm=arm.id):
                self.close(arm.gimbal.gear_ratio, defaults["gear_ratio"])
                self.close(arm.gimbal.tilt_limit_deg, defaults["tilt_limit_deg"])
                self.close(arm.gimbal.coupling, defaults["coupling"])
                for name in ("outer", "inner"):
                    axis = arm.gimbal.axis(name)
                    self.close(axis.servo_limit_deg, defaults[name]["servo_limit_deg"])
                    self.close(axis.us_per_deg, defaults[name]["us_per_deg"])
                    self.close(axis.sign, defaults[name]["sign"])
                    # Channels are the one thing an arm must state for itself.
                    self.assertEqual(axis.channel, self.cfg.raw["arms"][
                        [a.id for a in self.cfg.arms].index(arm.id)
                    ][name]["channel"])

    def test_every_axis_can_supply_the_travel_its_envelope_needs(self) -> None:
        """
        The config has to be mechanically self-consistent, not just well-formed.

        Reaching the full tilt envelope needs ``gear * limit`` of servo on the outer
        axis and ``gear * limit * (1 + coupling)`` on the inner one, because the inner
        command carries the outer ring's motion as well. A config that promises more
        tilt than its servos can deliver loads fine and then silently scales every
        request back, so it is worth failing here instead.
        """
        for arm in self.cfg.arms:
            gimbal = arm.gimbal
            needed = {
                "outer": gimbal.gear_ratio * gimbal.tilt_limit_deg,
                "inner": gimbal.gear_ratio * gimbal.tilt_limit_deg * (1.0 + abs(gimbal.coupling)),
            }
            for name, required in needed.items():
                with self.subTest(arm=arm.id, axis=name):
                    low, high = kin.servo_deg_window(gimbal.axis(name))
                    self.assertGreaterEqual(
                        min(abs(low), abs(high)),
                        required - 1e-9,
                        f"{arm.id}.{name} needs {required} deg of travel but has "
                        f"[{low}, {high}]",
                    )

    def test_the_full_tilt_envelope_is_actually_reachable(self) -> None:
        """Every corner of the tilt square must come back unscaled."""
        for arm in self.cfg.arms:
            limit = arm.gimbal.tilt_limit_deg
            for outer in (-limit, 0.0, limit):
                for inner in (-limit, 0.0, limit):
                    with self.subTest(arm=arm.id, tilt=(outer, inner)):
                        answer = kin.solve(arm.gimbal, outer, inner)
                        self.close(answer.scale, 1.0, tol=1e-9)

    def test_channel_conflicts_are_rejected(self) -> None:
        broken = json.loads(json.dumps(self.cfg.raw))
        broken["arms"][1]["outer"]["channel"] = broken["arms"][0]["outer"]["channel"]
        with self.assertRaisesRegex(vconfig.ConfigError, "claimed by both"):
            vconfig.from_dict(broken)

    def test_bad_sign_is_rejected(self) -> None:
        broken = json.loads(json.dumps(self.cfg.raw))
        broken["gimbal_defaults"]["outer"]["sign"] = 0
        with self.assertRaisesRegex(vconfig.ConfigError, "sign must be"):
            vconfig.from_dict(broken)

    # ------------------------------------------------------------------
    # tilt <-> servo
    # ------------------------------------------------------------------
    def test_zero_tilt_is_centered(self) -> None:
        answer = kin.solve(self.north.gimbal, 0.0, 0.0)
        self.assertEqual(answer.outer.pwm_us, 1500)
        self.assertEqual(answer.inner.pwm_us, 1500)
        self.close(answer.scale, 1.0)

    def test_forward_inverse_round_trip(self) -> None:
        for tilt_outer in (-22.5, -11.0, -0.5, 0.0, 3.25, 15.0, 22.5):
            for tilt_inner in (-22.5, -7.5, 0.0, 9.0, 22.5):
                with self.subTest(outer=tilt_outer, inner=tilt_inner):
                    servos = kin.servo_deg_for_tilt(self.north.gimbal, tilt_outer, tilt_inner)
                    back = kin.tilt_for_servo_deg(self.north.gimbal, *servos)
                    self.close(back[0], tilt_outer)
                    self.close(back[1], tilt_inner)

    def test_gear_ratio_and_coupling(self) -> None:
        """Outer travel is pure gearing; the inner servo also has to carry the outer term."""
        outer_only = kin.servo_deg_for_tilt(self.north.gimbal, 22.5, 0.0)
        self.close(outer_only[0], -45.0)
        # The inner axis holds still geometrically, so its servo must follow the outer ring.
        self.close(outer_only[1], -45.0)

        inner_only = kin.servo_deg_for_tilt(self.north.gimbal, 0.0, 22.5)
        self.close(inner_only[0], 0.0)
        self.close(inner_only[1], 45.0)

    def test_pwm_scale_is_500_to_2500_over_180_degrees(self) -> None:
        axis = self.north.gimbal.inner
        self.assertEqual(axis.deg_to_us(-90.0), 500)
        self.assertEqual(axis.deg_to_us(0.0), 1500)
        self.assertEqual(axis.deg_to_us(90.0), 2500)

    def test_inner_servo_needs_full_travel_at_the_corners(self) -> None:
        """
        Worst case is full tilt on both axes at once, and it lands exactly on the
        inner servo's mechanical stop. No headroom is left, which is why a trim
        offset on that axis costs corner reach.
        """
        facts = kin.describe_gimbal(self.north.gimbal)
        self.close(facts["innerServoNeededDeg"], 90.0, tol=1e-6)
        self.close(facts["outerServoNeededDeg"], 45.0, tol=1e-6)
        self.close(facts["innerHeadroomDeg"], 0.0, tol=1e-6)

    # ------------------------------------------------------------------
    # compatibility with the retired lookup table
    # ------------------------------------------------------------------
    def test_reproduces_legacy_cardinal_table(self) -> None:
        limit = self.north.gimbal.tilt_limit_deg
        for name, (outer_servo, inner_servo) in sorted(LEGACY_CARDINALS.items()):
            with self.subTest(cardinal=name):
                tilt = kin.tilt_for_servo_deg(self.north.gimbal, outer_servo, inner_servo)
                self.assertLessEqual(abs(tilt[0]), limit + 1e-9)
                self.assertLessEqual(abs(tilt[1]), limit + 1e-9)
                # Every legacy point was a full-deflection point.
                self.close(max(abs(tilt[0]), abs(tilt[1])), limit, tol=1e-9)

                again = kin.servo_deg_for_tilt(self.north.gimbal, *tilt)
                self.close(again[0], outer_servo)
                self.close(again[1], inner_servo)

    def test_legacy_cardinals_cover_every_corner_and_edge(self) -> None:
        """The old table was the tilt square's four corners and four edge midpoints."""
        limit = self.north.gimbal.tilt_limit_deg
        decoded = {
            (round(a, 6), round(b, 6))
            for a, b in (
                kin.tilt_for_servo_deg(self.north.gimbal, *servos)
                for servos in LEGACY_CARDINALS.values()
            )
        }
        expected = {
            (round(a, 6), round(b, 6))
            for a in (-limit, 0.0, limit)
            for b in (-limit, 0.0, limit)
            if not (a == 0.0 and b == 0.0)
        }
        self.assertEqual(decoded, expected)

    # ------------------------------------------------------------------
    # reachability
    # ------------------------------------------------------------------
    def test_over_range_request_is_scaled_not_clipped(self) -> None:
        """
        Asking for twice the available tilt must pull both axes back together.
        Clipping one axis alone would rotate the thrust vector away from the request.
        """
        answer = kin.solve(self.north.gimbal, 45.0, 22.5)
        self.assertTrue(answer.clamped)
        self.close(answer.scale, 0.5)
        self.close(answer.outer.tilt_deg / answer.inner.tilt_deg, 45.0 / 22.5, tol=1e-9)
        self.assertLessEqual(abs(answer.outer.tilt_deg), self.north.gimbal.tilt_limit_deg + 1e-9)

    def test_in_range_request_is_untouched(self) -> None:
        answer = kin.solve(self.north.gimbal, -12.0, 8.0)
        self.close(answer.scale, 1.0)
        self.close(answer.outer.tilt_deg, -12.0)
        self.close(answer.inner.tilt_deg, 8.0)
        self.assertFalse(answer.clamped)

    def test_trim_eats_into_reach(self) -> None:
        """A mechanical zero offset on the inner axis must reduce the reachable corner."""
        inner = self.north.gimbal.inner
        trimmed = vconfig.GimbalConfig(
            gear_ratio=self.north.gimbal.gear_ratio,
            tilt_limit_deg=self.north.gimbal.tilt_limit_deg,
            coupling=self.north.gimbal.coupling,
            outer=self.north.gimbal.outer,
            inner=vconfig.AxisConfig(
                channel=inner.channel,
                sign=inner.sign,
                center_us=inner.center_us,
                us_per_deg=inner.us_per_deg,
                servo_limit_deg=inner.servo_limit_deg,
                min_us=inner.min_us,
                max_us=inner.max_us,
                trim_deg=10.0,
            ),
        )
        self.close(kin.max_scale(self.north.gimbal, -22.5, 22.5), 1.0)
        self.assertLess(kin.max_scale(trimmed, -22.5, 22.5), 1.0)

    def test_workspace_outline_traces_the_tilt_square(self) -> None:
        limit = self.north.gimbal.tilt_limit_deg
        for a, b in kin.workspace_outline(self.north.gimbal, rays=360):
            self.assertLessEqual(abs(a), limit + 1e-6)
            self.assertLessEqual(abs(b), limit + 1e-6)
            self.close(max(abs(a), abs(b)), limit, tol=1e-6)

        # A square's inscribed circle is its half width, so uniform authority is the limit.
        self.close(kin.uniform_tilt_limit(self.north.gimbal, rays=360), limit, tol=1e-6)

    # ------------------------------------------------------------------
    # body frame
    # ------------------------------------------------------------------
    def test_centered_gimbal_thrusts_straight_up(self) -> None:
        vec = kin.thrust_unit_vector(self.north.mount_yaw_deg, 0.0, 0.0)
        self.close(vec[0], 0.0)
        self.close(vec[1], 0.0)
        self.close(vec[2], -1.0)

    def test_thrust_vector_is_a_unit_vector(self) -> None:
        for arm in self.cfg.arms:
            for tilt_outer in (-22.5, 0.0, 12.0, 22.5):
                for tilt_inner in (-22.5, 0.0, 7.0, 22.5):
                    with self.subTest(arm=arm.id, outer=tilt_outer, inner=tilt_inner):
                        vec = kin.thrust_unit_vector(arm.mount_yaw_deg, tilt_outer, tilt_inner)
                        self.close(math.sqrt(sum(v * v for v in vec)), 1.0)

    def test_inner_tilt_leans_thrust_aft_on_the_north_arm(self) -> None:
        """
        Positive inner tilt is a right-hand rotation about body +Y, which is nose-up,
        so the thrust vector leans aft. The small-angle helper must agree with the
        exact vector on both sign and axis.
        """
        forward, right = kin.gimbal_to_body_tilt(self.north.mount_yaw_deg, 0.0, 10.0)
        self.assertLess(forward, 0.0)
        self.close(right, 0.0)

        vec = kin.thrust_unit_vector(self.north.mount_yaw_deg, 0.0, 10.0)
        self.assertLess(vec[0], 0.0)
        self.close(vec[1], 0.0)

    def test_outer_tilt_leans_thrust_right_on_the_north_arm(self) -> None:
        """Positive outer tilt is a right-hand rotation about body +X, which tips thrust right."""
        forward, right = kin.gimbal_to_body_tilt(self.north.mount_yaw_deg, 10.0, 0.0)
        self.close(forward, 0.0)
        self.close(right, 10.0)

        vec = kin.thrust_unit_vector(self.north.mount_yaw_deg, 10.0, 0.0)
        self.assertGreater(vec[1], 0.0)
        self.close(vec[0], 0.0)

    def test_body_tilt_round_trip(self) -> None:
        for arm in self.cfg.arms:
            for forward in (-20.0, -3.0, 0.0, 11.0, 22.5):
                for right in (-22.5, 0.0, 6.0, 18.0):
                    with self.subTest(arm=arm.id, forward=forward, right=right):
                        tilt = kin.body_tilt_to_gimbal(arm.mount_yaw_deg, forward, right)
                        back = kin.gimbal_to_body_tilt(arm.mount_yaw_deg, *tilt)
                        self.close(back[0], forward)
                        self.close(back[1], right)

    def test_body_tilt_matches_exact_geometry_at_small_angles(self) -> None:
        for arm in self.cfg.arms:
            for forward, right in ((5.0, 0.0), (0.0, 5.0), (-4.0, 3.0)):
                with self.subTest(arm=arm.id, forward=forward, right=right):
                    tilt = kin.body_tilt_to_gimbal(arm.mount_yaw_deg, forward, right)
                    vec = kin.thrust_unit_vector(arm.mount_yaw_deg, *tilt)
                    self.close(math.degrees(math.asin(vec[0])), forward, tol=0.4)
                    self.close(math.degrees(math.asin(vec[1])), right, tol=0.4)

    def test_exact_lean_round_trip(self) -> None:
        for arm in self.cfg.arms:
            for forward in (-22.5, -6.0, 0.0, 9.0, 22.5):
                for right in (-22.5, 0.0, 4.5, 22.5):
                    with self.subTest(arm=arm.id, forward=forward, right=right):
                        tilt = kin.gimbal_for_thrust_lean(arm.mount_yaw_deg, forward, right)
                        back = kin.thrust_lean(arm.mount_yaw_deg, *tilt)
                        self.close(back[0], forward, tol=1e-7)
                        self.close(back[1], right, tol=1e-7)

    def test_exact_lean_means_the_same_thing_on_every_arm(self) -> None:
        """
        The point of mount_yaw: one body-frame demand produces the same thrust
        direction on all four arms even though their gimbals are bolted on at four
        different angles. With the exact solver this must hold to machine precision.
        """
        reference = None
        for arm in self.cfg.arms:
            answer = kin.solve_thrust_lean(arm, 8.0, -5.0)
            vec = kin.thrust_unit_vector(arm.mount_yaw_deg, *answer.tilt)
            self.close(answer.scale, 1.0, msg=f"{arm.id} should be reachable")
            if reference is None:
                reference = vec
                continue
            for axis, (got, want) in enumerate(zip(vec, reference)):
                self.close(got, want, tol=1e-12, msg=f"{arm.id} axis {axis}")

    def test_linear_map_error_is_bounded(self) -> None:
        """
        Pins down what the mixer's linearisation costs so docs/03-kinematics.md can
        quote a real number. Worst case is full deflection on both axes at once, and
        at +/-22.5 degrees it is 1.80 degrees.
        """
        worst = 0.0
        limit = self.north.gimbal.tilt_limit_deg
        steps = [limit * i / 8.0 for i in range(-8, 9)]
        for arm in self.cfg.arms:
            for tilt_outer in steps:
                for tilt_inner in steps:
                    linear = kin.gimbal_to_body_tilt(arm.mount_yaw_deg, tilt_outer, tilt_inner)
                    exact = kin.thrust_lean(arm.mount_yaw_deg, tilt_outer, tilt_inner)
                    worst = max(worst, abs(linear[0] - exact[0]), abs(linear[1] - exact[1]))
        self.close(worst, 1.795, tol=0.01)

    def test_outer_axis_loses_cosine_of_inner_deflection(self) -> None:
        """
        Explains the whole linearisation error in one line: the outer axis rotates an
        axis the inner one has already tilted, so its contribution to the body-frame
        lean is scaled by cos(tilt_inner). At full inner deflection that is a 7.6%
        gain loss on the outer axis, which the closed loop absorbs but tuning should
        know about.
        """
        limit = self.north.gimbal.tilt_limit_deg
        for tilt_inner in (0.0, limit / 2.0, limit):
            with self.subTest(inner=tilt_inner):
                _, right = kin.thrust_lean(self.north.mount_yaw_deg, limit, tilt_inner)
                predicted = math.degrees(
                    math.asin(math.cos(math.radians(tilt_inner)) * math.sin(math.radians(limit)))
                )
                self.close(right, predicted, tol=1e-9)

        _, full = kin.thrust_lean(self.north.mount_yaw_deg, limit, limit)
        self.close(full / limit, math.cos(math.radians(limit)), tol=0.01)

    def test_mount_yaw_swaps_which_servo_owns_which_body_axis(self) -> None:
        """
        North's gimbal is bolted at 0 degrees and East's at 90, so a purely forward
        lean is the inner servo's job on North and the outer servo's job on East.
        """
        north_tilt = kin.body_tilt_to_gimbal(self.cfg.arm("north").mount_yaw_deg, 10.0, 0.0)
        east_tilt = kin.body_tilt_to_gimbal(self.cfg.arm("east").mount_yaw_deg, 10.0, 0.0)
        self.close(north_tilt[0], 0.0)
        self.close(abs(north_tilt[1]), 10.0)
        self.close(east_tilt[1], 0.0)
        self.close(abs(east_tilt[0]), 10.0)

    # ------------------------------------------------------------------
    # whole vehicle
    # ------------------------------------------------------------------
    def test_yaw_tilt_pattern_cancels_force_and_produces_moment(self) -> None:
        """
        Yaw by tangential tilt: the four side forces must sum to zero while their
        moments about body Z add. Without that the vehicle would drift as it yaws.
        """
        pattern = kin.yaw_tilt_pattern(self.cfg.arms)
        self.assertEqual(len(pattern), len(self.cfg.arms))

        radius = self.cfg.frame.arm_length_m
        force_x = force_y = moment = 0.0
        for arm_id, forward, right in pattern:
            position = kin.arm_position(self.cfg.arm(arm_id), radius)
            force_x += forward
            force_y += right
            moment += position[0] * right - position[1] * forward

        self.close(force_x, 0.0, tol=1e-9)
        self.close(force_y, 0.0, tol=1e-9)
        self.assertGreater(moment, 0.0)
        # Every arm contributes its full lever arm, since the tilt is purely tangential.
        self.close(moment, radius * len(self.cfg.arms), tol=1e-9)

    def test_arm_positions_match_a_plus_layout(self) -> None:
        radius = self.cfg.frame.arm_length_m
        expected = {
            "north": (radius, 0.0),
            "east": (0.0, radius),
            "south": (-radius, 0.0),
            "west": (0.0, -radius),
        }
        for arm in self.cfg.arms:
            with self.subTest(arm=arm.id):
                position = kin.arm_position(arm, radius)
                self.close(position[0], expected[arm.id][0], tol=1e-9)
                self.close(position[1], expected[arm.id][1], tol=1e-9)

    def test_golden_vectors_are_current(self) -> None:
        """
        Guards the TypeScript port. After an intentional change, refresh with
        ``python3 Vector/tests/test_kinematics.py --write-golden``.
        """
        if not os.path.exists(GOLDEN_PATH):
            self.skipTest("golden file not generated yet")
        with open(GOLDEN_PATH, "r", encoding="utf-8") as handle:
            stored = json.load(handle)
        self.assertEqual(stored, build_golden(self.cfg))


def write_golden() -> None:
    cfg = vconfig.load()
    with open(GOLDEN_PATH, "w", encoding="utf-8") as handle:
        json.dump(build_golden(cfg), handle, indent=2)
        handle.write("\n")
    print(f"wrote {GOLDEN_PATH}")


if __name__ == "__main__":
    if "--write-golden" in sys.argv:
        write_golden()
    else:
        unittest.main()
