/**
 * Checks the TypeScript kinematics against the golden vectors generated by the
 * Python suite, so the two implementations cannot drift apart.
 *
 * The golden file is written by:
 *
 *     python3 Vector/tests/test_kinematics.py --write-golden
 *
 * If this fails after an intentional change to the Python module, regenerate the
 * file and read the diff before accepting it.
 */

import { describe, expect, it } from 'vitest'

import golden from '~tests/golden_kinematics.json'
import vehicle from '../../../../config/vector.json'
import {
  bodyTiltToGimbal,
  desiredLean,
  gimbalForThrustLean,
  gimbalToBodyTilt,
  maxScale,
  solve,
  thrustLean,
  thrustUnitVector,
  usToDeg,
  worldUpInBody,
} from './kinematics'
import type { ArmConfig, AxisConfig, GimbalConfig } from './types'

/**
 * Builds the camelCase config the TypeScript side expects out of the snake_case
 * JSON document, applying the same `gimbal_defaults` fallback as `config.py`.
 * The server normally does this; here we read the file directly so the test does
 * not need a running server.
 */
function buildArms(): ArmConfig[] {
  const defaults = (vehicle as any).gimbal_defaults
  const axis = (name: 'outer' | 'inner', raw: any): AxisConfig => {
    const base = { ...defaults[name], ...(raw ?? {}) }
    return {
      channel: base.channel,
      sign: base.sign ?? 1,
      centerUs: base.center_us ?? 1500,
      usPerDeg: base.us_per_deg ?? 11.11111,
      servoLimitDeg: base.servo_limit_deg ?? 45,
      minUs: base.min_us ?? 1000,
      maxUs: base.max_us ?? 2000,
      trimDeg: base.trim_deg ?? 0,
    }
  }

  return (vehicle as any).arms.map((raw: any): ArmConfig => {
    const gimbal: GimbalConfig = {
      gearRatio: defaults.gear_ratio,
      tiltLimitDeg: defaults.tilt_limit_deg,
      coupling: defaults.coupling,
      outer: axis('outer', raw.outer),
      inner: axis('inner', raw.inner),
    }
    return {
      id: raw.id,
      label: raw.label ?? raw.id,
      status: raw.status ?? 'live',
      live: (raw.status ?? 'live') === 'live',
      azimuthDeg: raw.azimuth_deg ?? 0,
      mountYawDeg: raw.mount_yaw_deg ?? 0,
      gimbal,
      motors: {},
    }
  })
}

const arms = buildArms()
const north = arms.find((arm) => arm.id === 'north')!
const goldenArms = (golden as any).arms as Record<string, GoldenSample[]>

interface GoldenSample {
  request: [number, number]
  scale: number
  tilt: [number, number]
  servoDeg: [number, number]
  pwmUs: [number, number]
  bodyTilt: [number, number]
  thrust: [number, number, number]
}

describe('golden vectors match the Python implementation', () => {
  for (const arm of arms) {
    const samples = goldenArms[arm.id]

    it(`${arm.id}: ${samples.length} samples`, () => {
      for (const sample of samples) {
        const [reqOuter, reqInner] = sample.request
        const answer = solve(arm.gimbal, reqOuter, reqInner)
        const where = `${arm.id} request=(${reqOuter}, ${reqInner})`

        expect(answer.scale, `${where} scale`).toBeCloseTo(sample.scale, 9)
        expect(answer.outer.tiltDeg, `${where} tilt outer`).toBeCloseTo(sample.tilt[0], 9)
        expect(answer.inner.tiltDeg, `${where} tilt inner`).toBeCloseTo(sample.tilt[1], 9)
        expect(answer.outer.servoDeg, `${where} servo outer`).toBeCloseTo(sample.servoDeg[0], 9)
        expect(answer.inner.servoDeg, `${where} servo inner`).toBeCloseTo(sample.servoDeg[1], 9)

        // Pulse widths are integers on both sides: they must agree exactly, since
        // this is the value that actually reaches the servo.
        expect(answer.outer.pwmUs, `${where} pwm outer`).toBe(sample.pwmUs[0])
        expect(answer.inner.pwmUs, `${where} pwm inner`).toBe(sample.pwmUs[1])

        const body = gimbalToBodyTilt(arm.mountYawDeg, answer.outer.tiltDeg, answer.inner.tiltDeg)
        expect(body[0], `${where} body forward`).toBeCloseTo(sample.bodyTilt[0], 9)
        expect(body[1], `${where} body right`).toBeCloseTo(sample.bodyTilt[1], 9)

        const thrust = thrustUnitVector(arm.mountYawDeg, answer.outer.tiltDeg, answer.inner.tiltDeg)
        for (let i = 0; i < 3; i += 1) {
          expect(thrust[i], `${where} thrust[${i}]`).toBeCloseTo(sample.thrust[i], 9)
        }
      }
    })
  }
})

describe('conventions', () => {
  it('a centred gimbal thrusts straight up', () => {
    for (const arm of arms) {
      const [x, y, z] = thrustUnitVector(arm.mountYawDeg, 0, 0)
      expect(x).toBeCloseTo(0, 12)
      expect(y).toBeCloseTo(0, 12)
      expect(z).toBeCloseTo(-1, 12)
    }
  })

  it('the pulse scale is 500..2500 us over 180 degrees', () => {
    expect(usToDeg(north.gimbal.inner, 500)).toBeCloseTo(-90, 3)
    expect(usToDeg(north.gimbal.inner, 1500)).toBeCloseTo(0, 12)
    expect(usToDeg(north.gimbal.inner, 2500)).toBeCloseTo(90, 3)
  })

  it('the inner servo needs its full 90 degrees at one pair of corners', () => {
    // The coupling term either adds to or cancels the inner axis' own travel,
    // depending on the sign of the outer tilt. With outer.sign = -1 and
    // coupling = +1, opposite-sign corners stack to the servo's mechanical stop
    // and same-sign corners cancel to centre. This is what sizes the hardware:
    // the inner servo must have twice the outer's travel even though both axes
    // move the same 22.5 degrees.
    expect(solve(north.gimbal, 22.5, -22.5).inner.servoDeg).toBeCloseTo(-90, 6)
    expect(solve(north.gimbal, -22.5, 22.5).inner.servoDeg).toBeCloseTo(90, 6)
    expect(solve(north.gimbal, 22.5, -22.5).inner.atLimit).toBe(true)

    expect(solve(north.gimbal, 22.5, 22.5).inner.servoDeg).toBeCloseTo(0, 6)
  })

  it('an over-range request is scaled, not clipped', () => {
    const answer = solve(north.gimbal, 45, 45)
    expect(answer.clamped).toBe(true)
    // Direction preserved: both axes pulled back by the same factor.
    expect(answer.outer.tiltDeg).toBeCloseTo(answer.inner.tiltDeg, 9)
    expect(maxScale(north.gimbal, 45, 45)).toBeCloseTo(0.5, 9)
  })

  it('an exact lean round-trips', () => {
    for (const arm of arms) {
      for (const [forward, right] of [
        [0, 0],
        [10, 0],
        [0, -8],
        [12, 12],
        [-20, 5],
      ] as [number, number][]) {
        const [outer, inner] = gimbalForThrustLean(arm.mountYawDeg, forward, right)
        const [gotForward, gotRight] = thrustLean(arm.mountYawDeg, outer, inner)
        expect(gotForward).toBeCloseTo(forward, 9)
        expect(gotRight).toBeCloseTo(right, 9)
      }
    }
  })

  it('the linear map round-trips', () => {
    for (const arm of arms) {
      const [outer, inner] = bodyTiltToGimbal(arm.mountYawDeg, 7, -4)
      const [forward, right] = gimbalToBodyTilt(arm.mountYawDeg, outer, inner)
      expect(forward).toBeCloseTo(7, 9)
      expect(right).toBeCloseTo(-4, 9)
    }
  })
})

describe('levelling law mirrors the server', () => {
  const law = {
    levelGain: 1,
    leadTimeS: 0,
    maxTiltFraction: 1,
    invertRoll: false,
    invertPitch: false,
    tiltCapDeg: 22.5,
  }

  it('a level airframe needs no lean', () => {
    const out = desiredLean(law, 0, 0, 0, 0)
    expect(out.forward).toBeCloseTo(0, 12)
    expect(out.right).toBeCloseTo(0, 12)
    expect(out.saturated).toBe(false)
  })

  it('nose up leans thrust forward, right side down leans it left', () => {
    expect(desiredLean(law, 0, 10, 0, 0).forward).toBeCloseTo(10, 6)
    expect(desiredLean(law, 10, 0, 0, 0).right).toBeCloseTo(-10, 6)
  })

  it('matches world up exactly inside the envelope', () => {
    for (const [roll, pitch] of [
      [0, 0],
      [8, 0],
      [0, -12],
      [5, 7],
      [-12, 14],
    ] as [number, number][]) {
      const out = desiredLean(law, roll, pitch, 0, 0)
      const up = worldUpInBody(roll, pitch)
      const expected = [
        (Math.asin(up[0]) * 180) / Math.PI,
        (Math.asin(up[1]) * 180) / Math.PI,
      ]
      expect(out.forward).toBeCloseTo(expected[0], 6)
      expect(out.right).toBeCloseTo(expected[1], 6)
    }
  })

  it('caps the lean at the mechanical limit without rotating it', () => {
    const out = desiredLean(law, -40, 40, 0, 0)
    expect(out.saturated).toBe(true)
    expect(Math.hypot(out.forward, out.right)).toBeCloseTo(22.5, 6)
    const uncapped = worldUpInBody(-40, 40)
    expect(out.forward / out.right).toBeCloseTo(
      Math.asin(uncapped[0]) / Math.asin(uncapped[1]),
      6,
    )
  })

  it('zero gain holds the gimbals with the airframe', () => {
    const out = desiredLean({ ...law, levelGain: 0 }, 15, 15, 0, 0)
    expect(out.forward).toBeCloseTo(0, 12)
    expect(out.right).toBeCloseTo(0, 12)
  })

  it('lead time extrapolates the attitude', () => {
    const out = desiredLean({ ...law, leadTimeS: 0.1 }, 0, 0, 0, 50)
    expect(out.forward).toBeCloseTo(5, 1)
  })
})
